blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jorge-moreira/ai-brain-tool/discussions
    about: Please ask questions and start discussions here