name: CI

on:
  pull_request:
    branches: [main, feature/app]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]

jobs:
  core-test:
    uses: ./.github/workflows/core-test.yml

  cli-test:
    uses: ./.github/workflows/cli-test.yml

  # TODO: Remove comment once electron tests are added
  #electron-test:
  #  uses: ./.github/workflows/electron-test.yml
